#pragma once

#define PRODUCT_VERSION_STRING	"2025 version 1.47"
#define VER_MAJOR	2025
#define VER_MINOR	1
#define VER_REV		47
#define VER_BUILD	502

#define TOSTRING(x) #x
#define VERSION_STRING	TOSTRING(VER_MAJOR) "." TOSTRING(VER_MINOR) "." TOSTRING(VER_REV) "." TOSTRING(VER_BUILD)
