#pragma once

#define PRODUCT_VERSION_STRING	"2024 version 1.2"
#define VER_MAJOR	2024
#define VER_MINOR	1
#define VER_REV		2
#define VER_BUILD	162

#define TOSTRING(x) #x
#define VERSION_STRING	TOSTRING(VER_MAJOR) "." TOSTRING(VER_MINOR) "." TOSTRING(VER_REV) "." TOSTRING(VER_BUILD)
